#! ---------------------------------------------------------------
#! WARNING THIS YAML
#! IS IN CHINESE!
#! ---------------------------------------------------------------



# I 侧边栏菜单
#
# 不要在链接里加入根目录。例如，`http://test.com/path/to/pages`，你应当填写 `path/to/pages`。
# 如果链接失效，试着去掉 `index.html`。
# 记得到第二部分去填写它的 icon。
# 所有内容都是可选的。如果要增加新的页面，可以仿照格式继续填写，并在 language 下增加它的页面名称。

# Menu 内的内容会显示在侧边栏。
Menu:
  Home: index.html
  Archives: archives/index.html
  Tags: tags/index.html
  Categories: categories/index.html
  About: somepage/about/index.html
  Message_board: somepage/chat/index.html
  Links: somepage/link/index.html
  Settings: somepage/settings/index.html

# 顶部栏也可以放一个页面。可选。
Topbar: somepage/say/index.html

# 搜索页面的链接。
Search: somepage/search/index.html



# II 菜单图标
#
# 使用 fontawesome 图标。链接：http://www.fontawesome.com.cn。

icon:
  Home: fa-home
  Archives: fa-tasks
  Tags: fa-tags
  Categories: fa-th-large
  About: fa-user-o
  Message_board: fa-commenting-o
  Links: fa-link
  Settings: fa-cog
  Topbar: fa-bell-o
  Search: fa-search



# III 评论
#
# 评论功能在不包含 "discomments: true" 的页面开启。
# 支持两个评论系统。

comments:
  # LiveRe（来必力）评论系统
  # 从这里得到你的 uid。
  # https://livere.com/insight/myCode
  livere:
    enable: false
    uid: 

  # Gitalk 评论系统
  # https://github.com/gitalk/gitalk
  gitalk:
    enable: true
    clientID: "''"
    clientSecret: "''"
    repo: "''"
    owner: "''"
    admin: "['']"
    proxy: "''"



# IV 自适应
#
# 根据设定的宽度（单位为 px）改变显示方式。

responsive:
  dividing_1: 1170
  dividing_2: 990
  # 这里隐去工具栏。
  dividing_3: 770
  # 这里隐去侧边栏。



# V 首页提示
#
# 以下是预设：
# <i class="fa fa-volume-up" aria-hidden="true"></i> 欢迎来到 cieu 的博客！希望我们能相互交流，共同进步～

site_warning:
  enable: root   # 可以取这些值：none | root | all。默认值是 none。
  text: "<i class='fa fa-volume-up' aria-hidden='true'></i> 改 ID 了。由 cieu 变更为 Yurchiu。"
  type: warning  # 可以取这些值：danger | warning | info | success。默认值是 default（灰色）。



# VI 版权信息

footer:          # 页脚版权信息。
  left: '©2019-2023 <a href="https://github.com/yz-hs">Yurchiu</a>. All rights reserved.'
  right: 'Theme <a href="https://github.com/yz-hs/cutie">Cutie</a>, by Yurchiu.'

copyright:       # 文末版权信息。
  enable: post   # 可以取这些值：all | post | disable。默认值是 disable。
                 # all: 在每个页面末尾显示。
                 # post: 只在每个博文末尾显示。
                
  statement: '本博客所有文章除特别声明外，均允许规范转载。转载请注明出处！'



# VII 博文摘要
#
# 在首页文章卡片中的摘要信息。

post_excerpt:
  mode: excerpt         # 可以取这些值：excerpt | noexcerpt。默认值是 excerpt。
                        # excerpt: 如果博文源文件中含有 "<!--more-->"，将会将它前面的内容作为摘要。
                        # noexcerpt: 所有文章被认为没有摘要。

  ifdefault: false      # 大前提：博文源文件中不含有 "<!--more-->"。
                        # ture：展示 "post_default_excerpt" 内容。
                        # false：展示博文的一部分。

  display: html         # 可以取这些值：html | text。默认值是 text。
                        # html: 仅当博文源文件中含有 "<!--more-->" 时，保留 html 标签。
                        # text: 任何情况下不保留 html 标签。

  post_default_excerpt: '<i class="fa fa-warning" aria-hidden="true"></i> 本文章无可提供的摘要 qwq。可能 Yurchiu 太懒了，或不适合做摘要。'
  length_excerpt: 150   # 当展示博文的一部分时，展示的文本字符数。默认是 30。

  # 注意：如果一篇博文源文件中不含有 "<!--more-->"，而 display 值为 html 时，则效果与 "display: text" 相同。 



# VIII 标签云

tag_cloud:
  color:               # 颜色渐变范围
    from: "#fff"       # night: #aaa
    to: "#fff"         # not-night: #fff
  font:                # 字体渐变范围（单位 px）
    from: 14
    to: 14



# IX 字体
#
# 字体，每空仅能填一种
# https://fonts.googleapis.com/css?family=...

# 主体字体（用于请求）
font: Montserrat # Saira Monda Montserrat
# 主体字体的实际名字（用于设值）
font_name: Montserrat
# 等宽字体，代码片段使用（用于请求）
mono_font: Roboto+Mono
# 等宽字体的实际名字（用于设值）
mono_font_name: "Roboto Mono"



# X 杂项

# 图片背景卡片 高度默认值
ImgCard_h: 30em

# Aplayer+Meting 底部播放器
meting:
  server: netease
  type: playlist
  id: 8524070964

# 图片加速 CDN，可选
imgcdn: 

# 自我简述
short_des: "An AFO whker."

# 头像
avatar:
  url: /img/new-avatar.jpg
  # 头像动效，可以取这些值：bounce | revolve | none，默认值是 none。
  effect: revolve

# 彩蛋
colored_eggs:
  # 可以取这些值：santa | natsuki | none，默认值是 none。
  type: natsuki
  width: 140px                       # 人物大小，仅对 natsuki 有用。
  time: 0.55s                        # 动画时间，仅对 natsuki 有用。
  bezier: cubic-bezier(0, 0, 0, 1)   # 贝塞尔曲线，仅对 natsuki 有用。
                                     # 对于 natsuki，可以在 source 文件夹中的 img 文件夹更改图片。

  # 可用作愚人节彩蛋                            
  reverse: false                     # 网页反转（只转一次）。
  hair: false                        # 你的屏幕上有头发。


# 博客默认配色
# 可以取这些值：std | white | night | none，默认值是 std。 "none" 非常特殊。
color_schemes: std

# 博客默认特殊效果
# 可以取这些值：none | grayscale | invert | blur，默认值是 none。
special: none

# 背景图片地址
bg_url: /img/new-bgp.jpg  # night-bgp.png

# 时间格式
# http://momentjs.cn/docs/#/parsing/string-format/
time_format: "YYYY-MM-DD, HH:mm:ss"

# 透明度，取值区间为 [0,1] 间的实数。
opacity: 1

# 图片崩掉后，会用它替换。
img_default: /img/error.jpg

# toolbar 文章显示个数。
toolbar_amount: 7



#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------



# 本主题使用的 CDN。
cdn:
  css:
    katex: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.15.6/katex.min.css
    gitalk: https://unpkg.com/gitalk/dist/gitalk.css
    googlefont: https://fonts.googleapis.com
    highlight: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/vs2015.min.css
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css
    bootstrap: https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css
    aplayer: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  js:
    jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
    anime: https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js
    pjax: https://cdnjs.cloudflare.com/ajax/libs/jquery.pjax/2.0.1/jquery.pjax.min.js
    gitalk: https://unpkg.com/gitalk/dist/gitalk.min.js
    highlight: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js
    sweetalert2: https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.17/sweetalert2.all.min.js
    sketch: https://cdn.staticfile.org/sketch.js/1.0/sketch.min.js
    bootstrap: https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js
    aplayer: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
    meting: https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js