#! ---------------------------------------------------------------
#! WARNING THIS YAML
#! IS IN CHINESE!
#! ---------------------------------------------------------------



# I 侧边栏菜单
#
# 填写链接。例如，`http://test.com/path/to/pages`，你应当填写 `path/to/pages/index.html`。
# 无 "/index.html" 后缀会阻止 Pjax。
# 记得在 II 菜单图标 填写它的 fontawesome icon。
# 菜单内容任意增删。如果要增，可以仿照格式继续填写，另外需要在 language 文件夹下增加菜单名称翻译。

# Menu 内的内容会显示在侧边栏。
Menu:
  Home: index.html
  Archives: archives/index.html
  Tags: tags/index.html
  Categories: categories/index.html
  Mood: somepage/mood/index.html
  About: somepage/about/index.html
  Message_board: somepage/chat/index.html
  Links: somepage/link/index.html
  Settings: somepage/settings/index.html

# 搜索页面的链接。
Search: somepage/search/index.html



# II 菜单图标
#
# 使用 fontawesome 图标。链接：http://www.fontawesome.com.cn。

icon:
  Home: fa-home
  Archives: fa-tasks
  Tags: fa-tags
  Categories: fa-th-large
  Mood: fa-photo
  About: fa-user-o
  Message_board: fa-commenting-o
  Links: fa-link
  Settings: fa-cog
  Search: fa-search



# III 评论
#
# 评论功能在不包含 "discomments: true" 的页面开启。
# 支持两个评论系统。

comments:
  # LiveRe（来必力）评论系统
  # 从这里得到你的 uid。
  # https://livere.com/insight/myCode
  livere:
    enable: false
    uid: 

  # Gitalk 评论系统
  # https://github.com/gitalk/gitalk
  gitalk:
    enable: true
    clientID: "''"
    clientSecret: "''"
    repo: "''"
    owner: "''"
    admin: "['']"
    proxy: "''"



# IV 自适应
#
# 根据设定的宽度（单位为 px）改变显示方式。

responsive:
  dividing_1: 1170
  dividing_2: 990
  # 这里隐去工具栏。
  dividing_3: 770
  # 这里隐去侧边栏。



# V 首页提示

site_warning:
  enable: root   # 可以取这些值：none | root | all。默认值是 none。
  text: "<i class='fa fa-volume-up'></i> 欢迎来到 Yurchiu 的博客！希望我们能相互交流，共同进步～"
  type: success  # 可以取这些值：danger | warning | info | success。



# VI 版权信息

footer:          # 页脚版权信息。
  left: '©2019-2023 <a href="https://github.com/yz-hs">Yurchiu</a>. All rights reserved.'
  right: 'Theme <a href="https://github.com/yz-hs/cutie">Cutie</a>, by Yurchiu.'

copyright:       # 文末版权信息。
  enable: post   # 可以取这些值：all | post | disable。默认值是 disable。
                 # all: 在每个页面末尾显示。
                 # post: 只在每个博文末尾显示。
                
  statement: '本博客所有文章除特别声明外，均允许规范转载。转载请注明出处！'



# VII 博文摘要
#
# 在首页文章卡片中的摘要信息。

post_excerpt:
  mode: excerpt         # 可以取这些值：excerpt | noexcerpt。默认值是 excerpt。
                        # excerpt: 如果博文源文件中含有 "<!--more-->"，将会将它前面的内容作为摘要。
                        # noexcerpt: 所有文章被认为没有摘要。

  ifdefault: false      # 大前提：博文源文件中不含有 "<!--more-->"。
                        # true：展示 "post_default_excerpt" 内容。
                        # false：展示博文的一部分。

  display: html         # 可以取这些值：html | text。默认值是 text。
                        # html: 仅当博文源文件中含有 "<!--more-->" 时，保留 html 标签。
                        # text: 任何情况下不保留 html 标签。

  post_default_excerpt: '<i class="fa fa-warning"></i> 本文章无可提供的摘要 qwq。可能 Yurchiu 太懒了，或不适合做摘要。'
  length_excerpt: 150   # 当展示博文的一部分时，展示的文本字符数。默认是 30。

  # 注意：如果一篇博文源文件中不含有 "<!--more-->"，而 display 值为 html 时，则效果与 "display: text" 相同。 



# VIII 标签云
#
# 位于工具栏。

tag_cloud:
  enable: true         # 是否启用
  color:               # 颜色渐变范围
    from: "#fff"       # night: #aaa
    to: "#fff"         # not-night: #fff
  font:                # 字体渐变范围（单位 px）
    from: 14
    to: 14



# IX 字体
#
# https://fonts.googleapis.com/css?family=...

# 引用的谷歌字体
fonts:
  - Montserrat
  - Roboto+Mono

# 字体家族
font_family: "Montserrat,sans-serif"
mono_font_family: "'Roboto Mono',sans-serif"



# X Aplayer+Meting 底部播放器

meting:
  enable: true
  server: netease
  type: playlist
  id: 8524070964



# XI 头像

avatar:
  url: /img/new-avatar.jpg
  # 头像动效，可以取这些值：bounce | revolve | none，默认值是 none。
  effect: revolve



# XII 博客彩蛋

colored_eggs:
  # 可以取这些值：santa | natsuki | none，默认值是 none。
  type: natsuki
  width: 140px                       # 人物大小，仅对 natsuki 有用。
  time: 0.55s                        # 动画时间，仅对 natsuki 有用。
  bezier: cubic-bezier(0, 0, 0, 1)   # 贝塞尔曲线，仅对 natsuki 有用。
                                     # 对于 natsuki，可以在 source 文件夹中的 img 文件夹更改图片。

  # 可用作愚人节彩蛋                            
  reverse: false                     # 网页反转（只转一次）。
  hair: false                        # 你的屏幕上有头发。



# XIII 杂项

# 侧边栏是否显示标签个数等
sidebar_num: true

# 工具栏是否显示“博客信息”
toolbar_info: true

# 工具栏是否显示第三栏
toolbar_third: true

# 你的 GitHub 名称，用于某些链接
github_name: yz-hs

# 图片背景卡片 高度默认值
ImgCard_h: 30em

# 图片加速 CDN，可选
# 对头像、背景图片、图片文章卡片等进行加速。
# Jsdelivr 提供加速服务：https://cdn.jsdelivr.net/gh/[you]/[yourBlog]
imgcdn: 

# 自我简述
short_des: "An AFO whker."

# 博客默认配色
# 可以取这些值：std | white | night | none，默认值是 std。 "none" 非常特殊。
color_schemes: std

# 博客默认特殊效果
# 可以取这些值：none | grayscale | invert | blur，默认值是 none。
special: none

# 背景图片地址
bg_url: /img/new-bgp.jpg  # night-bgp.png

# 时间格式
# http://momentjs.cn/docs/#/parsing/string-format/
time_format: "YYYY-MM-DD, HH:mm:ss"

# 博客界面透明度，取值为属于区间 [0,1] 的实数。
opacity: 1

# 图片无法加载，会用它替换。
img_default: /img/error.jpg

# 工具栏“随机文章”等的显示文章个数。
toolbar_amount: 7



#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------



# 本主题使用的 CDN。
cdn:
  css:
    katex: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.15.6/katex.min.css
    gitalk: https://unpkg.com/gitalk/dist/gitalk.css
    googlefont: https://fonts.googleapis.com
    highlight: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/vs2015.min.css
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css
    bootstrap: https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css
    aplayer: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  js:
    jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
    anime: https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js
    pjax: https://cdnjs.cloudflare.com/ajax/libs/jquery.pjax/2.0.1/jquery.pjax.min.js
    gitalk: https://unpkg.com/gitalk/dist/gitalk.min.js
    highlight: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js
    sweetalert2: https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.17/sweetalert2.all.min.js
    sketch: https://cdn.staticfile.org/sketch.js/1.0/sketch.min.js
    bootstrap: https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js
    aplayer: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
    meting: https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js